### ISSUE TITLE
首先感谢作者分享！其次我不太明白作者您这边的坐标基准是如何确定的？坐标原点在哪里呢？因为我发现正常的16：9四个顶点好像无法应用作者您的这个坐标

### ISSUE THREAD

**Issue by hezhiming1995** [woshica/JiaGuoMeng-AutoClicker#11]
感谢作者新添了一个国家之光弹窗，我之前也没有发现这个，睡醒才发现出问题了！

**Comment by woshica** [comment]
这个坐标是蓝叠内使用的坐标，定义的是坐标点在手机屏幕的x、y轴上所占的百分比。比如(50, 50)就是屏幕的正中间，(0, 0)是左上角，(0, 100)是左下角，etc。
