### ISSUE TITLE
自动升级建筑好像无效

### ISSUE THREAD

**Issue by dazzulay** [woshica/JiaGuoMeng-AutoClicker#12]
点了一下右侧的按钮然后就关闭了

**Comment by dazzulay** [comment]
python JiaGuoMeng.py -lvup 0 --train
使用参数

**Comment by dazzulay** [comment]
https://imgur.com/a/Ooxo5ZL
视频预览

**Comment by woshica** [comment]
这个可能是因为性能没跟上，脚本在点击右侧按钮之后没有等它下面的升级按钮升起来就进行了下一步的操作，导致操作无效；你可以在python文件里面开头设置的那些变量那里手动修改一下upgradeInterval，把数值调大一些，这样脚本在点击右侧的按钮之后会等待更长的时间之后再进行下一步。

**Comment by dazzulay** [comment]
感谢 换了个图形引擎就好了
