### ISSUE TITLE
执行python JiaGuoMeng.py -all出错

### ISSUE THREAD

**Issue by viliv715** [woshica/JiaGuoMeng-AutoClicker#15]
C:\Users\viliv\Desktop\JiaGuoMeng-AutoClicker-master>python JiaGuoMeng.py -all
Traceback (most recent call last):
  File "JiaGuoMeng.py", line 314, in <module>
    nm.export(i)
  File "JiaGuoMeng.py", line 142, in export
    func(*args, **kwargs)
  File "JiaGuoMeng.py", line 248, in autoUpgrade
    for everybuilding in self.buildingsNeedUpgrade:
TypeError: 'NoneType' object is not iterable

**Comment by woshica** [comment]
你需要在运行的时候加上-epicId和-lvup
比如py JiaGuoMeng.py -lvup 3 -epicId 1 2 5 -all，其中3指的是你需要升级的建筑的编号，1 2 5指的是你的史诗级建筑的编号（收火车货物的时候可以选择只收取这些建筑上的货物）
