### ISSUE TITLE
QQ授权按钮位置坐标

### ISSUE THREAD

**Issue by gitkz** [woshica/JiaGuoMeng-AutoClicker#21]
能否麻烦告知如何获得正确的授权按钮坐标？在我的模拟器上，这个按钮是横贯整个屏幕的，所以X坐标应该没问题，Y坐标是跟模拟器的原型home按钮在一条线上，请问坐标如何计算？程序里面的那个数字是百分比吗？
"qqLogin": (71.57, 82.77), 这个是没问题的，可以点到
"qqLogin2": (50.0, ?) 这个我试了几个都不对，应该是比82.77要大的数值。

**Comment by woshica** [comment]
程序里面的那个数字确实是百分比；
你可以在脚本录制器中新建一个脚本，然后点击一次屏幕，停止录制，再导出脚本，这样就可以获得你所点击的位置的坐标了。
