### ISSUE TITLE
没有创建自动收取金币的文件

### ISSUE THREAD

**Issue by lukenYang** [woshica/JiaGuoMeng-AutoClicker#3]
我看了下代码，if else 那没有执行autoCollect()，还有能不能做一个升级政策的

**Comment by watashihame** [comment]
autoCollect()的功能已经被整合入其他函数，生成时会加入autoCollect()函数内的操作。
升级政策牵扯到政策数据，可能需要用CV，目前没有考虑。

**Comment by lukenYang** [comment]
我搞错了，原来参数是直接写死的，不是传进去的。。
