### ISSUE TITLE
python JiaGuoMeng.py -epicId [4,5,6]报错

### ISSUE THREAD

**Issue by osgg** [woshica/JiaGuoMeng-AutoClicker#6]
c:\jia>python JiaGuoMeng.py -epicId [4,5,6]
usage: JiaGuoMeng.py [-h] [-epicId N [N ...]] [-lvup N [N ...]] [--train]
                     [--yellow-only]
JiaGuoMeng.py: error: argument -epicId: invalid int value: '[4,5,6]'
是我的输入方式有问题么

**Comment by woshica** [comment]
-epicId [4,5,6] 改为 -epicId 4,5,6 即可，不要加中括号。
另外，如果改完之后open那行报错，在根目录创建一个叫output的文件夹即可。我稍后会在代码中修复这个问题。
